In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
import numpy as np

# Introduction to pandas Data Structures

## Series

In [4]:
obj = pd.Series([4, 7, -5, 3])

In [5]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])

In [9]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [11]:
obj2['a']

-5

In [12]:
obj2['d'] = 6

In [13]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [15]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 *2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [20]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [21]:
obj3 = pd.Series(sdata)

In [22]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4.name = 'population'

In [31]:
obj4.index.name = 'state'

In [32]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [34]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [35]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

In [36]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [37]:
frame = pd.DataFrame(data)

In [38]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [39]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [40]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [41]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])

In [42]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [43]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [44]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [45]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [46]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [47]:
frame2['debt'] = 12

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5    12
two    2001    Ohio  1.7    12
three  2002    Ohio  3.6    12
four   2001  Nevada  2.4    12
five   2002  Nevada  2.9    12
six    2003  Nevada  3.2    12

In [49]:
frame2['debt'] = np.arange(6.)

In [50]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [51]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [52]:
frame2['debt'] = val

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [54]:
frame2['eastern'] = frame2.state == 'Ohio'

In [55]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [56]:
del frame2['eastern']

In [57]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [58]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [59]:
frame3 = pd.DataFrame(pop)

In [60]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [61]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [62]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [63]:
frame3['Ohio'][:-1]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [64]:
frame3['Nevada'][:2]

2001    2.4
2002    2.9
Name: Nevada, dtype: float64

In [65]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [66]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [67]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [68]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [69]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [70]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Objects

In [71]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [72]:
index = obj.index

In [73]:
index

Index(['a', 'b', 'c'], dtype='object')

In [74]:
obj

a    0
b    1
c    2
dtype: int64

In [75]:
index[1:]

Index(['b', 'c'], dtype='object')

In [78]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [79]:
labels = pd.Index(np.arange(3))

In [80]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [81]:
obj2 = pd.Series([1.5,-2.5,0], index=labels)

In [82]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [83]:
obj2.index is labels

True

In [84]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [85]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [86]:
'Ohio' in frame3.columns

True

In [87]:
2003 in frame.index

False

In [88]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [89]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [90]:
obj3 = pd.Series([1.5,-2.5,0,3], index=dup_labels)

In [91]:
obj3

foo    1.5
foo   -2.5
bar    0.0
bar    3.0
dtype: float64

# Essential Functionality

## Reindexing

In [92]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [93]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [94]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [95]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [96]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [97]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [98]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [99]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

In [100]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [101]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [102]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [103]:
states = ['Texas', 'Utah', 'California']

In [104]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [105]:
frame2.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['Utah'] not in index"

## Dropping Entries from an Axis

In [106]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [107]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [108]:
new_obj = obj.drop('c')

In [109]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [110]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [111]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [112]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [113]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [115]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [116]:
obj.drop('c', inplace=True)

In [117]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## Indexing, Selection, and Filtering

In [118]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [119]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [122]:
obj['b']

1.0

In [128]:
obj[1]

1.0

In [123]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [129]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [130]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [131]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [133]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [134]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [135]:
obj['b':'c'] = 5

In [136]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [137]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [138]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [142]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [157]:
data[1:2]

one  two  three  four
Colorado    4    5      6     7

In [146]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [158]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [159]:
data[data < 5] = 0

In [160]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc

In [161]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [162]:
??data.loc

In [163]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [164]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [165]:
data.iloc[[1,2], [3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [167]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [168]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [169]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [171]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## Integer Indexes

In [172]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [175]:
ser[-1]

KeyError: -1

In [176]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [181]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [186]:
ser2[-3]

0.0

In [187]:
ser[:1]

0    0.0
dtype: float64

# "

> use `loc` (for labels) or `iloc` (for integers)

# "

In [190]:
ser.loc[:1] # inclusive

0    0.0
1    1.0
dtype: float64

In [192]:
ser2.iloc[:1] # exclusive

a    0.0
dtype: float64

## Arithmetic and Data Alignment

In [193]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [194]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [195]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [197]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [198]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [199]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [200]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [201]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [210]:
df1 = pd.DataFrame({'A': [1, 2]})

df2 = pd.DataFrame({'B': [3, 4]})

In [211]:
df1

A
0  1
1  2

In [212]:
df2

B
0  3
1  4

In [214]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [234]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [236]:
df2.loc[1, 'b'] = np.nan

In [237]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [238]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [235]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [239]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [240]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [241]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [242]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

#### Operations between DataFrame and Series

In [243]:
arr = np.arange(12.).reshape((3,4))

In [244]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [245]:
arr[0]

array([0., 1., 2., 3.])

In [246]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [247]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [252]:
series = frame.iloc[0]

In [253]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [254]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [255]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [256]:
series2 = pd.Series(range(3), index=['b','e','f'])

In [257]:
series2

b    0
e    1
f    2
dtype: int64

In [258]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [261]:
series3 = frame['d']

In [262]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [263]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [264]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function Application and Mapping

In [296]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [274]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [297]:
frame

b         d         e
Utah   -1.244559  2.013559 -0.131685
Ohio   -0.119349 -1.410169  0.393988
Texas  -0.772974  0.472739  0.538724
Oregon  1.350844 -1.592807 -0.177298

In [298]:
np.abs(frame)

b         d         e
Utah    1.244559  2.013559  0.131685
Ohio    0.119349  1.410169  0.393988
Texas   0.772974  0.472739  0.538724
Oregon  1.350844  1.592807  0.177298

In [299]:
f = lambda x: x.max() - x.min()

In [300]:
frame.apply(f)

b    2.595403
d    3.606366
e    0.716022
dtype: float64

In [301]:
frame.apply(f, axis='columns')

Utah      3.258118
Ohio      1.804157
Texas     1.311698
Oregon    2.943651
dtype: float64

In [302]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [303]:
frame.apply(f)

b         d         e
min -1.244559 -1.592807 -0.177298
max  1.350844  2.013559  0.538724

In [304]:
format = lambda x: '%.2f' % x

In [305]:
frame.applymap(format)

b      d      e
Utah    -1.24   2.01  -0.13
Ohio    -0.12  -1.41   0.39
Texas   -0.77   0.47   0.54
Oregon   1.35  -1.59  -0.18

In [308]:
frame['e'].map(format)

Utah      -0.13
Ohio       0.39
Texas      0.54
Oregon    -0.18
Name: e, dtype: object

## Sorting and Ranking

In [6]:
obj = pd.Series(range(4), index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [8]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [9]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three', 'one'],
                    columns=['d','a','b','c'])

In [10]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [11]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [12]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [13]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [14]:
obj = pd.Series([4, 7, -3, 2])

In [15]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [18]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [19]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [24]:
frame = pd.DataFrame({'b': [4,7,-3,2], 'a': [0,1,0,1]})

In [25]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [26]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [28]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [6]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [7]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [8]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [9]:
obj.rank(method='max', ascending=False)

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [10]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})

In [11]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [14]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## Axis Indexes with Duplicate Labels

In [15]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [16]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [17]:
obj.index.is_unique

False

In [18]:
obj['a']

a    0
a    1
dtype: int64

In [19]:
obj['c']

4

In [20]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [21]:
df

0         1         2
a  2.046450  0.830759  1.786581
a  1.862989  0.075505  1.153748
b -0.273983 -1.075315 -0.065700
b  1.909836  0.827338 -0.969644

In [22]:
df.loc['b']

0         1         2
b -0.273983 -1.075315 -0.065700
b  1.909836  0.827338 -0.969644

# Summarizing and Computing Descriptive

In [13]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                 index=['a','b','c','d'],
                 columns=['one', 'two'])

In [14]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [6]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [7]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [8]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [9]:
df.idxmax()

one    b
two    d
dtype: object

In [15]:
df.idxmin()

one    d
two    b
dtype: object

In [18]:
df.cumsum(axis=0)

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [19]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [20]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [21]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [22]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## Correlation and Covariance

In [4]:
import pandas_datareader.data as web

In [6]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [8]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [20]:
volume

AAPL        IBM        MSFT        GOOG
Date                                                      
2017-08-17  111762400.0  4625517.0  22977500.0  25544000.0
2017-08-18  109712400.0  4343724.0  18761500.0  26854000.0
2017-08-21  105474000.0  3337472.0  17734800.0  18868000.0
2017-08-22   86418400.0  2661442.0  14343700.0  23334000.0
2017-08-23   77596400.0  4234522.0  13766500.0  21804000.0
...                 ...        ...         ...         ...
2022-08-11   57149200.0  3501900.0  20065900.0  16671600.0
2022-08-12   67946400.0  2766900.0  22601900.0  16106600.0
2022-08-15   54091700.0  2791200.0  18085700.0  15525000.0
2022-08-16   56180100.0  4312200.0  18074400.0  15617500.0
2022-08-17   43674853.0  1862547.0   9649482.0   9045193.0

[1259 rows x 4 columns]

In [21]:
price

AAPL         IBM        MSFT        GOOG
Date                                                      
2017-08-17   37.454857  106.045532   68.175026   45.549000
2017-08-18   37.369457  105.291840   68.259789   45.533501
2017-08-21   37.300640  105.766678   67.939629   45.333000
2017-08-22   37.910412  106.279198   68.890694   46.234501
2017-08-23   37.957867  107.130882   68.476372   46.349998
...                ...         ...         ...         ...
2022-08-11  168.490005  132.539993  287.019989  119.820000
2022-08-12  172.100006  134.009995  291.910004  122.650002
2022-08-15  173.190002  134.929993  293.470001  122.879997
2022-08-16  173.029999  136.559998  292.709991  122.510002
2022-08-17  174.360001  137.429596  291.690002  120.593399

[1259 rows x 4 columns]

In [10]:
returns = price.pct_change()

In [11]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-08-11 -0.004432  0.007909 -0.007401 -0.006879
2022-08-12  0.021426  0.011091  0.017037  0.023619
2022-08-15  0.006334  0.006865  0.005344  0.001875
2022-08-16 -0.000924  0.012080 -0.002590 -0.003011
2022-08-17  0.007687  0.006368 -0.003485 -0.015644

In [12]:
returns['MSFT'].corr(returns['IBM'])

0.4755048265936761

In [13]:
returns['MSFT'].cov(returns['IBM'])

0.00015251918625903323

In [14]:
returns.MSFT.corr(returns.IBM)

0.4755048265936761

In [15]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.435603  0.759658  0.684843
IBM   0.435603  1.000000  0.475505  0.443141
MSFT  0.759658  0.475505  1.000000  0.786931
GOOG  0.684843  0.443141  0.786931  1.000000

In [16]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000409  0.000151  0.000287  0.000259
IBM   0.000151  0.000294  0.000153  0.000142
MSFT  0.000287  0.000153  0.000350  0.000275
GOOG  0.000259  0.000142  0.000275  0.000350

In [17]:
returns.corrwith(returns.IBM)

AAPL    0.435603
IBM     1.000000
MSFT    0.475505
GOOG    0.443141
dtype: float64

In [19]:
returns.corrwith(volume)

AAPL   -0.082251
IBM    -0.115284
MSFT   -0.068894
GOOG   -0.080716
dtype: float64

## Unique Values, Value Counts, and Membership

In [34]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [35]:
uniques = obj.unique()

In [36]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [31]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [37]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [38]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [39]:
mask = obj.isin(['b','c'])

In [40]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [41]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [42]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [43]:
unique_vals = pd.Series(['c','b','a'])

In [44]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [45]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [46]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [47]:
result = data.apply(pd.value_counts).fillna(0)

In [48]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0